name: _test3
channels:
  - defaults
  - conda-forge
dependencies:
  - cython >=0.28.4
  - docutils
  - ipyparallel
  - ipython >=4.0
  - matplotlib>=1.5
  - numba
  - numexpr
  - numpy >=1.15.4
  - pathlib
  - python >=3.0
  - uncertainties
  - zope.interface>=3.8.0

  #- ipywidgets
  #- ipykernel        # Use with nb_conda_kernels so jupyter sees this kernel
    
  # For testing
  - coverage
  - docutils
  - flake8
  - persist
  - pytest
  - pytest-cov
  - pytest-flake8
  - pytest-xdist
  - scipy >=0.17.1
  - uncertainties
  - pyfftw
    
  #- pylint
  #- mock
  #- pep8

  # For documents
  - sphinx
  - mock
  - sphinx_rtd_theme
  
  # Needed for . mmf_setup and hg ccom
  - notebook

  # My stuff
  - mmf_setup>=0.1.11
  - persist >=3.0
  - husl
