name: _test2
channels:
  - defaults
  - conda-forge
dependencies:
  - python=2
  - matplotlib>=1.5
  #- scipy>=0.17.1
  #- numpy
  - numexpr
  - uncertainties
  - ipyparallel
  - zope.interface>=3.8.0
  - docutils
  - cython
  - numba

  #- ipywidgets
  #- ipykernel        # Use with nb_conda_kernels so jupyter sees this kernel
    
  # For testing
  - pytest-flake8
  - pytest-cov
  - pytest-runner
  #- pylint
  #- mock
  #- pep8

  # For documents
  - sphinx
  - mock
  - sphinx_rtd_theme
  
  # Needed for . mmf_setup and hg ccom
  - notebook
  
  - pip:
    - mmf_setup>=0.1.11
    - persist
    - husl
    
