{% set name = "mmfutils" %}

package:
  name: "{{ name|lower }}"
  version: "{{ load_setup_py_data().version }}"

source:
  path: .
  #hg_rev: {{ version }}
  #hg_url: ssh://bitbucket.org/mforbes/mmfutils-fork

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "
  #script: "{{ PYTHON }} setup.py build --no-deps"
channel:
  - mforbes
  - conda-forge
  
requirements:
  build:
    - python {{ python }}
  host:
    - python {{ python }}
    - setuptools >=18.0      # automatically handles Cython extensions
    - cython >=0.28.4
    - numba
  run:
    - python {{ python }}
    - zope.interface >=3.8.0
    - husl
    - pathlib
    - backports.tempfile
    - persist

test:
  source_files:
    - '*'
  imports:
    - {{ name }}
  requires:
    - docutils
    - pytest
    - pytest-cov
    - pytest-flake8
    - pytest-xdist
    - coverage
    - flake8
    - ipython >=4.0
    - ipyparallel
    - matplotlib
    - persist >=3.0
    - numba
    - numpy >=1.15.4
    - numexpr
    - uncertainties
    - scipy
  commands:
    - pytest -n4

about:
  home: https://bitbucket.org/mforbes/mmfutils
  license: BSD
  license_family: BSD
  license_file: LICENSE.txt
  summary: Small set of utilities, containers, and interfaces.
  doc_url: http://mmfutils.readthedocs.org
  dev_url: https://bitbucket.org/mforbes/mmfutils-fork
